spring.application.name=ProductService

#Below is the required block of code for the connection of Database to our Spring Application
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/learningJava
spring.datasource.username=mukund
##spring.datasource.password=secret

#For AWS Database Connection
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

#To connect with AWS provided Redis
#spring.data.redis.port=6379
#spring.data.redis.host=awsredis's url


#logging.level.org.springframework.web=TRACE

server.port = ${SERVER_PORT}

#Configurations for making this service a Eureka Client
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
