spring.application.name=APIGateway

server.port=7070

#Configurations for making this service a Eureka Client
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

#---------------------------- Routing Logic --------------------------------

#Routing logic for Product Service
spring.cloud.gateway.server.webflux.routes[0].id=ProductService
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/products/*
spring.cloud.gateway.server.webflux.routes[0].uri=lb://ProductService

#Routing logic for User Service
spring.cloud.gateway.server.webflux.routes[1].id=UserService
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/user/*
spring.cloud.gateway.server.webflux.routes[1].uri=lb://UserService